### PR TITLE
Move checked files to separate folder

### PR DESCRIPTION
**Pull request by kant2002**
Mainly to cleanly work with source files. For all practical purposes should be the same.

### CODE REVIEW

**Comment by hacklex** [comment]
Looks good. Will have to modify sources to look for cached files in obj/, as I mainly keep checked files to speed up my emacs's fstar-mode, so we should have the source files reflect checked files move. Gotta check whether this will work properly via push-options.

**Comment by hacklex** [comment]
I'm actually unsure if I really should include checked files in repository at all. They're not source code after all. Probably gitignoring them is even better.

**Comment by kant2002** [comment]
I do rebase, and if you also want to keep `checked` outside source control, you can merge this PR.

**Comment by hacklex** [comment]
Looks good. Thank you!

**Pull request merged**
